---
- name: 'install packages for key retrival'
  become: yes 
  ansible.builtin.package:
    name:
     - ca-certificates
    state: present
- name: 'create keyring directory'
  become: yes
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    recurse: true
    mode: '0755'
- name: 'get key from docker source'
  become: yes
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0444'
- name: 'remove conflicting packages'
  become: yes
  ansible.builtin.package:
    name:
      - podman
      - buildah
    state: absent
- name: 'update apt and install common packages'
  become: yes
  ansible.builtin.apt:
    update_cache: true
    name: "{{ item }}"
    state: present
  loop: "{{ common_packages}}"
- name: 'start and enable docker'
  become: yes
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
...
