  services:
    plex:
      image: plexinc/pms-docker
      environment:
        - TZ=US/EST
        - PLEX_CLAIM:claim-unoxGoEGiexVxcDkB4PF      
      network_mode: host
      volumes:
        - /mnt/sda1/shared:/config
        - /mnt/sda1/shared/Music:/Music
      restart: unless-stopped
    slskd:
      image: slskd/slskd:latest
      environment:
        - SLSKD_UMASK=001
        - SLSKD_DOWNLOADS_DIR=/complete
        - SLSKD_INCOMPLETE_DIR=/incomplete
        - SLSKD_REMOTE_CONFIGURATION=true
        - SLSKD_SHARED_DIR=/complete
      ports:
        - 5030:5030\tcp
        - 5031:5031\tcp
        - 50300:50300\tcp
      volumes: 
        - /mnt/sda1/shared:/app
        - /mnt/sda1/shared/Music:/complete
        - /mnt/sda1/shared/pending:/incomplete
      restart: unless-stopped
